{
 "title": "Circuit Breaker Tiny Bank",
 "description": "Show Circuit Breaker metrics from resilience4j via Spring Boot actuator",
 "tags": [
  "circuit-breaker",
  "resilience4j",
  "perfana",
  "perfana-template"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "failure rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{service=\"tiny-bank-service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "slow calls rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_slow_call_rate{service=\"tiny-bank-service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Circuit Breaker State - BalanceService",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{service=\"tiny-bank-service\", name=\"balanceService\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Circuit Breaker State - AccountService",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{service=\"tiny-bank-service\", name=\"accountService\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Slow calls - BalanceService",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_slow_calls{name=\"balanceService\", service=\"tiny-bank-service\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Slow calls - AccountService",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_slow_calls{name=\"accountService\", service=\"tiny-bank-service\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "calls per second BalanceService",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(resilience4j_circuitbreaker_calls_seconds_count{name=\"balanceService\"}[$__rate_interval])) by (kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "calls per second AccountService",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(resilience4j_circuitbreaker_calls_seconds_count{name=\"accountService\"}[$__rate_interval])) by (kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "max seconds BalanceService",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_calls_seconds_max{service=\"tiny-bank-service\", name=\"balanceService\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "max seconds AccountService",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_calls_seconds_max{service=\"tiny-bank-service\", name=\"accountService\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  }
 ]
}