package io.perfana.tinybank.wiremock;

import com.github.tomakehurst.wiremock.common.FileSource;
import com.github.tomakehurst.wiremock.extension.Parameters;
import com.github.tomakehurst.wiremock.extension.ResponseTransformer;
import com.github.tomakehurst.wiremock.http.Request;
import com.github.tomakehurst.wiremock.http.Response;

import java.util.Random;

public class ExampleTransformer extends ResponseTransformer {

    private final Random random = new Random();

    @Override
    public Response transform(Request request, Response response, FileSource files, Parameters parameters) {
        // Get failure percentage from parameters or use default 0%
        int failurePercentage = parameters.containsKey("failurePercentage")
                ? parameters.getInt("failurePercentage")
                : 0;

        // Randomly determine if this should be a failure response
        boolean shouldFail = random.nextInt(100) < failurePercentage;

        if (shouldFail) {
            // Return a failure response
            return Response.response()
                    .status(503)
                    .headers(response.getHeaders())
                    .body("{\"error\": \"Service Unavailable\", \"message\": \"Random failure generated by ExampleTransformer\"}")
                    .build();
        }

        // Return the original response for success cases
        return response;
    }

    @Override
    public String getName() {
        return "example-transformer";
    }

    @Override
    public boolean applyGlobally() {
        return false;
    }
}