services:
  influxdb:
    image: influxdb:1.11
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6 # Automatically create 'k6' database
      INFLUXDB_ADMIN_USER: admin # Admin username
      INFLUXDB_ADMIN_PASSWORD: admin_password # Admin password
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./init-influxdb.sh:/docker-entrypoint-initdb.d/init-influxdb.sh
    restart: always

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - influxdb
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector:0.119.0
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    command:
      - "--config=/etc/otel-local-config.yaml"
    volumes:
      - ./otel-local-config.yaml:/etc/otel-local-config.yaml
    restart: always

  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init-tempo:
    image: &tempoImage grafana/tempo:2.8.1
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo_data:/var/tempo

  memcached:
    image: memcached:1.6.38
    container_name: memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m  # Set the maximum memory usage
      - MEMCACHED_THREADS=4       # Number of threads to use

  tempo:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      #- "4317:4317"  # otlp grpc
      #- "4318:4318"  # otlp http
      #- "9411:9411"   # zipkin
    depends_on:
      - init-tempo
      - memcached

volumes:
  influxdb_data:
  grafana_data:
  tempo_data: