services:
  influxdb:
    image: influxdb:1.12.4
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6 # Automatically create 'k6' database
      INFLUXDB_ADMIN_USER: admin # Admin username
      INFLUXDB_ADMIN_PASSWORD: admin_password # Admin password
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./init-influxdb.sh:/docker-entrypoint-initdb.d/init-influxdb.sh
    restart: always

  grafana:
    image: grafana/grafana:12.3.8
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - influxdb
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus:v3.13.0
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector:0.155.0
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    command:
      - "--config=/etc/otel-local-config.yaml"
    volumes:
      - ./otel-local-config.yaml:/etc/otel-local-config.yaml
    restart: always

volumes:
  influxdb_data:
  grafana_data: