receivers:
  zipkin:
    endpoint: 0.0.0.0:9411
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        include_metadata: true
        endpoint: 0.0.0.0:4318
processors:
  attributes:
    actions:
      - key: "system_under_test"
        action: insert
        from_context: metadata.system_under_test
        #value: "tiny-bank"
        #from_attribute: system_under_test
      - key: "test_environment"
        action: insert
        from_context: metadata.test_environment
        #value: "silver"
        #from_attribute: "test_environment"
      - key: "service"
        action: insert
        from_context: metadata.service
        #value: "tiny-bank-service"
        #from_attribute: service
  batch:
    timeout: 100ms
    send_batch_size: 10

extensions:
  zpages: {}
exporters:
  debug:
    verbosity: detailed
  prometheusremotewrite:
      endpoint: "http://prometheus:9090/api/v1/write"
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: "DEBUG"
      development: true
      encoding: "json"
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [attributes]
      exporters: [prometheusremotewrite]
#    logs:
#      receivers: [otlp]
#      processors: []
#      exporters: [debug]
    traces:
      receivers: [otlp, zipkin]
      processors: [attributes]
      exporters: [otlp]
